version: '3'
services:
  chat:
    container_name: websocket
    build: ./
    command: node index.js
    environment:
      DEBUG: chat-websocket:*
      NODE_ENV: dev
      PORT: 3000
      RDB_HOST: rethinkdb
      RDB_PORT: 28015
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/chat-websocket/app
    networks:
      - app-tier
    depends_on:
      - rethinkdb

  rethinkdb:
    image: rethinkdb:2.3.5
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - db-data:/data
    networks:
      - app-tier

volumes:
  db-data:

networks:
  app-tier:
